### ISSUE TITLE
Custom methods with arrays

### ISSUE THREAD

**Issue by steveostudios** [p3sn/magento-soap-promise#3]
I'm racking my brain here. This could very well be that I have no idea what I am doing. If so, sorry!
I'm using a custom method and everything works perfect!  

```
const args = {
  productId: 3670
};
return mag.customCall("catalogProductInfo", args).then(item => {
  return buildResource(item)
});
```

But according to Magento's docs, I should be able to place an array of additional attributes in to get as well. I've tried this with SOAPUI and it works, too!

```
<urn:catalogProductInfo soapenv:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
  <sessionId xsi:type="xsd:string">xxxxxxxxxxxx</sessionId>
  <productId xsi:type="xsd:string">3670</productId>
  <storeView xsi:type="xsd:string">1</storeView>
  <attributes xsi:type="urn:catalogProductRequestAttributes">
    <!--You may enter the following 2 items in any order-->
    <!--Optional:-->
    <attributes xsi:type="urn:ArrayOfString" soapenc:arrayType="xsd:string[]"/>
    <!--Optional:-->
    <additional_attributes xsi:type="urn:ArrayOfString" soapenc:arrayType="xsd:string[2]">
      <item xsi:type="xsd:string">author</item>
      <item xsi:type="xsd:string">royalty</item>
    </additional_attributes>
  </attributes>
  <identifierType xsi:type="xsd:string">?</identifierType>
</urn:catalogProductInfo>
```

Which returns:
```
<info xsi:type="ns1:catalogProductReturnEntity">
  <product_id xsi:type="xsd:string">3670</product_id>
  ...
  <additional_attributes SOAP-ENC:arrayType="ns1:associativeEntity[1]" xsi:type="ns1:associativeArray">
    <item xsi:type="ns1:associativeEntity">
      <key xsi:type="xsd:string">author</key>
      <value xsi:type="xsd:string">209</value>
    </item>
    <item xsi:type="ns1:associativeEntity">
      <key xsi:type="xsd:string">royalty</key>
      <value xsi:type="xsd:string">0.7</value>
    </item>
  </additional_attributes>
</info>
```
I'm trying to do this same thing with this package but can't figure out if the reason it's not working is because I am dumb and I'm doing it wrong or handling this sort of thing is out of the scope of the package.

**Comment by p3sn** [comment]
Hi, 

I created a dev branch where additional arguments are optional. 
It should work like this:
return mag.getProduct(<value_like_before>, ['ean', 'another_custom_attribute']).then(result => {....

Regards, Peter

**Comment by steveostudios** [comment]
Peter! You are a genius! 
Thank you soooo much for this. This works perfectly! Thank you for adding in the fix and so much for what you do!

**Comment by steveostudios** [comment]
Hey Peter. Is there anyway you can push this as a new version on npm?
