### ISSUE TITLE
When trying to apply a complex filter in a custom call catalogProductList, the complex filter does not get applied as expected

### ISSUE THREAD

**Issue by hrghauri** [p3sn/magento-soap-promise#4]
I am either having a problem understand Magento documentation or the api is not behaving as expected.

```
mag.connect().then( sessionid => {

    let args ={
        complex_filter: {
            key: 'name',
            value: {
                key: 'like',
                value: 'prefixName %'
            }
        }
    }

    return mag.customCall('catalogProductList',args)
}).then(result =>{
    console.log(result)
}).catch( error => {
    console.log(error);
}) 
```

I expect that a subset of products get returned, specifically those whose name starts with the `prefixName`. But all the products get returned. Am I doing something wrong?

Any help would be much appreciated. Thanks!

**Comment by p3sn** [comment]
Hi, 

Is this related to: https://github.com/p3sn/magento-soap-promise/issues/3 ?

Regards, Peter

**Comment by hrghauri** [comment]
It seems similar but its more complex. According to Magento documentation https://devdocs.magento.com/guides/m1x/api/soap/catalog/catalogProduct/catalog_product.list.html

There are nested associative Arrays which are put inside complex_filter to filter. Apparently, I can not seem to figure out how to translate that into Javascript object as args.

**Comment by hrghauri** [comment]
After trying many things, finally I was able to get it working. Turns out there was a complex_filter inside complex_filter. 


```
    let args ={
        filters:{
            complex_filter:{
                complex_filter:{
                    key:"name",
                    value: {
                        key: "like",
                        value: "prefixName  %"
                    }
                }
            }
        }
    }

```

Many thanks!
